### ISSUE TITLE
0.6.0 Release Checklist

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/openstudio-standards#1712]
Timeline:
5 April 2024 Code Freeze
12 April 2024 Release Candidate
19 April 2024 Release

- [x] Merge module refactors except for HVAC, ServiceWaterHeating, and Refrigeration
- [x] Merge Standards data PRs
- [x] Merge Appendix G branch updates
- [x] Merge NRCAN branch updates and regression models
- [ ] Refactor ComStock data handling
- [x] Update CI to use OS 3.7.0
- [x] Update gemspec with new description and homepage
- [x] Update version
- [x] Fix major issues with OS develop
