### ISSUE TITLE
Heat Pump Water Heater Support

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/openstudio-standards#557]
**Summary**
Add wrapped-condenser and pumped-condenser heat pump water heater object methods to openstudio-standards.

**Background**
Heat pump water heaters (HPWHs) are a key technology for grid decarbonization.  They are currently modeled in openstudio-standards by adjusting the part load efficiency curve for an electric mixed water heater object.  This is substantially faster than using a stratified tank method that the residential teams uses to model small wrapped-condenser HPWHs.  Small commercial establishments may use a residential-type wrapped-condenser HPWH, while larger establishments use a pumped-condenser HPWH placed outdoors.

**Tasks**
 - [ ] Decide whether to keep the part load efficiency curve adjustment method, or use the stratified tank model
 - [ ] Determine standard efficiencies to use for commercial type wrapped-condenser and pumped-condenser HPWHs
 - [ ] Determine prevalence of wrapped-condenser and pumped-condenser variants
 - [ ] Project future efficiency levels for HPWHs
 
If using the stratified tank method:
 - [ ] update sizing method in openstudio-standards to scale HPWH (current hard-sized for single 80 gal tank)
 - [ ] add separate methods for wrapped-condenser and pumped-condenser variants
 - [ ] research performance curves for pumped condensers

**Notes from 18 Oct 2018 meeting with residential team**
- the residential team is considering speed-up methods for wrapped condenser modeling in EnergyPlus, perhaps using a TRNSYS modeling, with a goal to finish this work in 6-12 months ahead of the next major E+ release.  They may use our approach of the part load efficiency curve.
- the full residential heat pump water heater measure allows the user to account for ducted units, in the case the water heater condenser exchanges air in a zone it is not physically located in
- a separate task is determine how to model losses from distribution systems for central HPWHs.  BEOpt has some methods to handle re-circulation loops.
- performance rating methods for heat pump water heaters use UEF, which is similar to the old energy factor (EF) method, but uses a different draw profile
- 2nd generation heat pump water heaters are much more efficient than 1st generation
- Ben Larson and Jeff Robertson are the main points of contact

**Comment by mdahlhausen** [comment]
Added with #1420.
Additional work would be to add different specifications for HPWHs of different sizes, and breakout larger sizes into a bank of HPWHs.
